language: r
warnings_are_errors: true
cache: packages

addons:
  homebrew:
      packages:
        - mactex

jobs:
  include:
    - stage: unit tests
      r: oldrel
    - stage: unit tests, code coverage and deploy pkgdown website
      os: linux
      dist: xenial
      r: release
      r_packages:
        - covr
        - pkgdown
      after_success:
        - Rscript -e 'covr::codecov()'
        - Rscript -e 'pkgdown::build_site()'
      deploy:
        provider: pages
        keep_history: true
        github_token: $GITHUB_TOKEN
        on:
          all_branches: master
        local_dir: docs
    # - stage: unit tests
    #   os: osx
    #   r: release
    - stage: unit tests
      os: linux
      dist: bionic
      r: devel

/Library/TeX/texbin/tlmgr: unexpected return value from verify_checksum: -5

2.55s$ sudo tlmgr install inconsolata upquote courier courier-scaled helvetic

notifications:
  email:
    recipients:
      - kevin.cazelles@gmail.com
