language: r
warnings_are_errors: true
cache: packages

jobs:
  include:
    - stage: unit tests
      r: 3.2
    - stage: unit tests
      r: 3.3
    - stage: unit tests, code coverage and deploy pkgdown website
      os: linux
      dist: xenial
      r: release
      r_packages:
        - covr
        - pkgdown
      env:
        - NOT_CRAN=true
        - R_CODECOV=true
      deploy:
        skip_cleanup: true
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        local_dir: dev
    - stage: unit tests
      os: osx
      r: release
      env: NOT_CRAN=true
    - stage: unit tests
      os: linux
      dist: bionic
      r: devel
      env: NOT_CRAN=false


notifications:
  email:
    recipients:
      - kevin.cazelles@gmail.com
