language: r
warnings_are_errors: true
sudo: required

notifications:
  email:
    recipients:
      - s.vissault@yahoo.fr
      - kevin.cazelles@gmail.com

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
