language: r
warnings_are_errors: true
cache: packages

jobs:
  include:
    - stage: Check package
      r: oldrel
    - stage: Check package, code coverage and deploy pkgdown website
      os: linux
      dist: xenial
      r: release
      r_packages:
        - covr
        - pkgdown
      after_success:
        - Rscript -e 'covr::codecov()'
        - mkdir docs
        - git fetch origin gh-pages:gh-pages
        - git --work-tree=docs checkout gh-pages -- .
        - Rscript -e 'pkgdown::build_site()'
      deploy:
        provider: pages
        name: TraviSteve
        skip_cleanup: true
        keep_history: true
        github_token: $GITHUB_TOKEN
        on:
          branch: master
        local_dir: docs
    - stage: Check package
      os: osx
      r: release
    - stage: Check package
      os: linux
      dist: bionic
      r: devel

notifications:
  email:
    recipients:
      - kevin.cazelles@gmail.com
