language: r
warnings_are_errors: true
sudo: required

notifications:
  slack:
    rooms: insileco:3OxNTMMQsOZubgPEXCrXEwx7
    on_success: always
    on_failure: always #change or never
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "See on Travis: %{build_url}"
      - "duration: %{duration}"
  email:
    recipients:
      - kevin.cazelles@gmail.com

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true