language: r
warnings_are_errors: true
sudo: required

notifications:
  slack:
    rooms: insileco:3OxNTMMQsOZubgPEXCrXEwx7
    on_success: always
    on_failure: always #change or never
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Dave est une fille Build details: %{build_url}"
  email:
    recipients:
      - kevin.cazelles@gmail.com

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
