language: r
warnings_are_errors: true
cache: packages

jobs:
  include:
    - stage: unit tests
      r: oldrel
    - stage: unit tests, code coverage and deploy pkgdown website
      os: linux
      dist: xenial
      r: release
      r_packages:
        - covr
        - pkgdown
      after_success: Rscript -e 'covr::codecov()'
      deploy:
        skip_cleanup: true
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        on:
          all_branches: true
          condition: '"$TRAVIS_BRANCH" == "master" || -n "$TRAVIS_TAG"'
    - stage: unit tests
      os: osx
      r: release
    - stage: unit tests
      os: linux
      dist: bionic
      r: devel


notifications:
  email:
    recipients:
      - kevin.cazelles@gmail.com
